### ISSUE TITLE
Unable to run experiments/GIB_node_exp.py file successfully

### ISSUE THREAD

**Issue by TianQi-777** [snap-stanford/GIB#2]
Hello, thank you for sharing.   
When I run `experiments/GIB_node_exp.py`, I meet the following problems. 
1. There seems to be a bug with the `repara_all_layers` of the parameter input. [(here)](https://github.com/snap-stanford/GIB/blob/a5b625c38f65feda0413eba81b2ccf5dac8f1a98/experiments/GIB_node_exp.py#L113)
```
parser.add_argument('--reparam_all_layers', type=str, default="\(-2,\)", help='Whether to reparameterize all layers.')
```
When I run the code, the following error appears.
```
Traceback (most recent call last):
  File "GIB_node_exp.py", line 145, in <module>
    reparam_all_layers = eval_tuple(args.reparam_all_layers)
  File "../pytorch_net/util.py", line 727, in eval_tuple
    arg_return = eval(arg_return)
  File "<string>", line 1
    \(-2,\)
          ^
SyntaxError: unexpected character after line continuation character
```
I changed `"\(-2,\)"` to `(-2)` to solve this problem. Is this a bug in the code?

2. More importantly, when I run GAT version of `experiments/GIB_node_exp.py` (Cora dataset), the following error occurs (`self.propagate` of `GATConv` reports an error [(here)](https://github.com/snap-stanford/GIB/blob/a5b625c38f65feda0413eba81b2ccf5dac8f1a98/experiments/GIB_node_model.py#L315)). 
```
Traceback (most recent call last):
  File "GIB_node_exp.py", line 311, in <module>
    save_best_model=save_best_model,
  File "../experiments/GIB_node_model.py", line 1216, in train
    beta2=beta2)
  File "../experiments/GIB_node_model.py", line 978, in train_model
    logits, reg_info = model(data)
  File "/home/tianqi/anaconda3/envs/th17_sc2410_geo/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "../experiments/GIB_node_model.py", line 772, in forward
    x, ixz, structure_kl_loss = layer(x, data.edge_index)
  File "/home/tianqi/anaconda3/envs/th17_sc2410_geo/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "../experiments/GIB_node_model.py", line 339, in forward
    out = self.propagate(edge_index, size=size, x=x)
  File "/home/tianqi/anaconda3/envs/th17_sc2410_geo/lib/python3.7/site-packages/torch_geometric/nn/conv/message_passing.py", line 253, in propagate
    out = self.aggregate(out, **aggr_kwargs)
  File "/home/tianqi/anaconda3/envs/th17_sc2410_geo/lib/python3.7/site-packages/torch_geometric/nn/conv/message_passing.py", line 288, in aggregate
    reduce=self.aggr)
  File "/home/tianqi/anaconda3/envs/th17_sc2410_geo/lib/python3.7/site-packages/torch_scatter/scatter.py", line 159, in scatter
    return scatter_sum(src, index, dim, out, dim_size)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/home/tianqi/anaconda3/envs/th17_sc2410_geo/lib/python3.7/site-packages/torch_scatter/scatter.py", line 12, in scatter_sum
                out: Optional[torch.Tensor] = None,
                dim_size: Optional[int] = None) -> torch.Tensor:
    index = broadcast(index, src, dim)
            ~~~~~~~~~ <--- HERE
    if out is None:
        size = list(src.size())
  File "/home/tianqi/anaconda3/envs/th17_sc2410_geo/lib/python3.7/site-packages/torch_scatter/utils.py", line 13, in broadcast
    for _ in range(src.dim(), other.dim()):
        src = src.unsqueeze(-1)
    src = src.expand_as(other)
          ~~~~~~~~~~~~~ <--- HERE
    return src
RuntimeError: The expanded size of the tensor (8) must match the existing size (13264) at non-singleton dimension 1.  Target sizes: [13264, 8, 16].  Tensor sizes: [1, 13264, 1]
```
I checked the input of the error line as follows:
```
# edge_index.shape = torch.Size([2, 13264])
# size=None
# x.shape = torch.Size([2708, 128])
out = self.propagate(edge_index, size=size, x=x)
```
Is there a good solution? Looking forward to your reply.

**Comment by TianQi-777** [comment]
I found the reason because my version of pytorch_geometric is too high (1.7.0)

**Comment by sepideh-nsf** [comment]
> I found the reason because my version of pytorch_geometric is too high (1.7.0)

Hi,
Thank you for sharing your experience!
I would appreciate it if you specify which versions of Torch, torch-sparse, torch-geometric, and torch-scatter you are using.
